// Arq_Hex_Angular/src/app/infraestructure/layout/components/MovieCard/MovieCard.tsx
import { Movie } from '../../../../domain/models/Movie';
import { formatDate } from '../../../shared/helpers/FormatDate.helper';
import { formatDecimal } from '../../../shared/helpers/FormatDecimal.helper';
import { languageToCountryMap } from '../../../shared/helpers/LanguageToCountry.helper';
import './MovieCard.css';

interface MovieCardProps {
  movie: Movie;
}

export const MovieCard = ({ movie }: MovieCardProps) => {
  const IMAGE_BASE_URL = import.meta.env.VITE_IMAGE_BASE_URL;

  const { id, title, overview, original_language, poster_path, backdrop_path, release_date, vote_average } = movie;
  const imageUrl = `${IMAGE_BASE_URL}${poster_path}`;
  const backdropUrl = `${IMAGE_BASE_URL}${backdrop_path}`;
  const countryCode = languageToCountryMap[original_language] || original_language;
  const languageFlagUrl = countryCode
    ? `https://raw.githubusercontent.com/Yummygum/flagpack-core/main/svg/m/${countryCode}.svg
`
    : undefined;

  return (
    <div className='movie-card' key={id}>
      <img src={backdropUrl} alt={title} className='movie-card__backdrop' loading='lazy' />
      <img src={imageUrl} alt={title} className='movie-card__image' title={title} loading='eager' />
      <span className='movie-card__rating'>{formatDecimal(vote_average)}</span>
      <img
        src={languageFlagUrl}
        alt={original_language}
        className='movie-card__flag'
        title={`Original Language: ${original_language.toUpperCase()}`}
        loading='lazy'
      />
      <div className='movie-card__header'>
        <h2 className='movie-card__title'>{title}</h2>
        <p className='movie-card__release-date'>{formatDate(release_date)}</p>
      </div>
      <p className='movie-card__overview'>{overview}</p>
    </div>
  );
};

// Arq_Hex_Angular/src/app/infraestructure/layout/components/movie-card/movie-card.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { environment } from '../../../../../environments/environment';
import { Movie } from '../../../../domain/models/movie.model';
import { formatDate } from '../../../shared/helpers/format-date.helper';
import { formatDecimal } from '../../../shared/helpers/format-decimal.helper';
import { languageToCountryMap } from '../../../shared/helpers/language-to-country.helper';

@Component({
  selector: 'app-movie-card',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './movie-card.component.html',
  styleUrls: ['./movie-card.component.scss'],
})
export class MovieCardComponent {
  @Input() movie!: Movie;

  IMAGE_BASE_URL = environment.imageBaseUrl;

  get imageUrl(): string {
    return `${this.IMAGE_BASE_URL}${this.movie.poster_path}`;
  }

  get backdropUrl(): string {
    return `${this.IMAGE_BASE_URL}${this.movie.backdrop_path}`;
  }

  get languageFlagUrl(): string | undefined {
    const countryCode =
      languageToCountryMap[this.movie.original_language] ||
      this.movie.original_language;
    return `https://raw.githubusercontent.com/Yummygum/flagpack-core/main/svg/m/${countryCode}.svg`;
  }

  formatDate(date: string): string {
    return formatDate(date);
  }

  formatDecimal(value: number): string {
    return formatDecimal(value);
  }
}

<div class="movie-card">
  <img
    [src]="backdropUrl"
    [alt]="movie.title"
    class="movie-card__backdrop"
    loading="lazy"
  />
  <img
    [src]="imageUrl"
    [alt]="movie.title"
    class="movie-card__image"
    [title]="movie.title"
    loading="eager"
  />
  <span class="movie-card__rating">{{
    formatDecimal(movie.vote_average)
  }}</span>
  <img
    *ngIf="languageFlagUrl"
    [src]="languageFlagUrl"
    [alt]="movie.original_language"
    class="movie-card__flag"
    [title]="'Original Language: ' + movie.original_language.toUpperCase()"
    loading="lazy"
  />
  <div class="movie-card__header">
    <h2 class="movie-card__title">{{ movie.title }}</h2>
    <p class="movie-card__release-date">{{ formatDate(movie.release_date) }}</p>
  </div>
  <p class="movie-card__overview">{{ movie.overview }}</p>
</div>
