// Arq_Hex_React/src/infraestructure/layout/components/MovieList/MovieList.tsx
import { useEffect, useState } from 'react';
import { Movie } from '../../../../domain/models/Movie';
import { MESSAGES } from '../../../shared/constants/Messages';
import { MovieCard } from '../../components/MovieCard/MovieCard';
import './MovieList.css';

interface MovieListProps {
  functionToFetch: () => Promise<Movie[]>;
}

export const MovieList = ({ functionToFetch }: MovieListProps) => {
  const [movies, setMovies] = useState<Movie[]>([]);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const movies = await functionToFetch();
        setMovies(movies);
      } catch (error) {
        console.error(MESSAGES.ERROR.FETCHING, error);
      }
    };

    fetchData();
  }, [functionToFetch]);

  return (
    <div className='movie-list'>
      {movies.map((movie) => (
        <MovieCard key={movie.id} movie={movie} />
      ))}
    </div>
  );
};

// Arq_Hex_Angular/src/app/infraestructure/layout/components/movie-list/movie-list.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input, OnChanges, OnInit } from '@angular/core';
import { Movie } from '../../../../domain/models/movie.model';
import { MESSAGES } from '../../../shared/constants/messages.constant';
import { MovieCardComponent } from '../movie-card/movie-card.component';

@Component({
  selector: 'app-movie-list',
  imports: [CommonModule, MovieCardComponent],
  templateUrl: './movie-list.component.html',
  styleUrls: ['./movie-list.component.scss'],
})
export class MovieListComponent implements OnInit, OnChanges {
  @Input() functionToFetch!: () => Promise<Movie[]>;
  movies: Movie[] = [];

  constructor() {}

  ngOnInit(): void {
    this.getMovies();
  }

  ngOnChanges(): void {
    this.getMovies();
  }

  getMovies(): void {
    this.functionToFetch()
      .then((res) => {
        this.movies = res;
      })
      .catch((error) => {
        console.error(MESSAGES.ERROR.FETCHING, error);
      });
  }
}

<div class="movie-list">
  <app-movie-card *ngFor="let movie of movies" [movie]="movie" />
</div>
