// Arq_Hex_Angular/src/app/infraestructure/layout/pages/Home.tsx
import { useState } from 'react';
import { Movie } from '../../../domain/models/Movie';
import { Footer } from '../components/Footer/Footer';
import { MovieList } from '../components/MovieList/MovieList';
import './Home.css';

interface HomeProps {
  getPopularMoviesUseCase: { execute: () => Promise<Movie[]> };
  getTopRatedMoviesUseCase: { execute: () => Promise<Movie[]> };
}

export const Home = ({ getPopularMoviesUseCase, getTopRatedMoviesUseCase }: HomeProps) => {
  const [activeFetch, setActiveFetch] = useState<'popular' | 'top'>('popular');

  const handleToggle = () => {
    setActiveFetch((prev) => (prev === 'popular' ? 'top' : 'popular'));
  };

  const getFetchFunction = () => {
    return activeFetch === 'popular' ? getPopularMoviesUseCase.execute() : getTopRatedMoviesUseCase.execute();
  };

  return (
    <div className='home'>
      <div className='home__header'>
        <h1>{activeFetch === 'popular' ? 'Popular Movies' : 'Top Rated Movies'}</h1>

        <button onClick={handleToggle} className='toggle-button'>
          {activeFetch === 'popular' ? 'Show Top Rated' : 'Show Popular'}
        </button>
      </div>

      <MovieList functionToFetch={getFetchFunction} />
      <Footer />
    </div>
  );
};

// Arq_Hex_Angular/src/app/infraestructure/layout/pages/home.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnChanges, OnInit } from '@angular/core';
import { GetPopularMoviesUseCase } from '../../../application/usecases/get-popular-movies.usecase';
import { GetTopRatedMoviesUseCase } from '../../../application/usecases/get-top-rated-movies.usecase';
import { Movie } from '../../../domain/models/movie.model';
import { FooterComponent } from '../components/footer/footer.component';
import { MovieListComponent } from '../components/movie-list/movie-list.component';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [CommonModule, MovieListComponent, FooterComponent],
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss'],
})
export class HomeComponent implements OnChanges, OnInit {
  activeFetch: 'popular' | 'top' = 'popular';

  functionToFetch: () => Promise<Movie[]> = () =>
    this.getPopularMoviesUseCase.execute();

  constructor(
    private getPopularMoviesUseCase: GetPopularMoviesUseCase,
    private getTopRatedMoviesUseCase: GetTopRatedMoviesUseCase
  ) {}

  toggleFetch(): void {
    this.activeFetch = this.activeFetch === 'popular' ? 'top' : 'popular';

    this.functionToFetch =
      this.activeFetch === 'popular'
        ? () => this.getPopularMoviesUseCase.execute()
        : () => this.getTopRatedMoviesUseCase.execute();
  }

  ngOnChanges(): void {
    this.toggleFetch();
  }

  ngOnInit(): void {
    this.toggleFetch();
  }
}

<div class="home">
  <div class="home__header">
    <h1>
      {{ activeFetch === 'popular' ? 'Popular Movies' : 'Top Rated Movies' }}
    </h1>
    <button class="toggle-button" (click)="toggleFetch()">
      {{ activeFetch === 'popular' ? 'Show Top Rated' : 'Show Popular' }}
    </button>
  </div>

  <app-movie-list [functionToFetch]="functionToFetch" />
  <app-footer />
</div>
